apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenor-service
  labels:
    app: tenor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenor-service
  template:
    metadata:
      labels:
        app: tenor-service
    spec:
      containers:
        - name: tenor-service
          image: matismbk/tenor-service:latest
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: tenor-storage
              mountPath: /app/prisma

          env:
            - name: DATABASE_URL
              value: "file:/app/prisma/tenor.db"
            - name: JWT_SECRET
              value: "change-me"
            - name: TENOR_API_KEY
              value: "API TOKEN"
            - name: PORT
              value: "5000"

          # Vérifie si l'app répond
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          # Vérifie si l'app est prête à recevoir du trafic
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: tenor-storage
          persistentVolumeClaim:
            claimName: tenor-service-pvc